import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header/header";
import Footer from "./Footer/footer";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="flex flex-col min-h-screen">
      <NextTopLoader
  color="#E94560"
  template='<div class="bar" role="bar"><div class="peg"></div></div> </div>'
/>
        <Header></Header>
        <main className="flex-col flex justify-center w-full">{children}</main>
        
        <Footer></Footer>
      </body>
    </html>
  );
}
